
[character]
success_symbol = '[ğŸ€ â¯](bold green) '
error_symbol = '[ğŸ€ â¯](bold red) '
vimcmd_symbol = '[ğŸ€ â®](bold green) '
vimcmd_replace_one_symbol = '[ğŸ€ â®](bold purple) '
vimcmd_replace_symbol = '[ğŸ€ â®](bold purple) '
vimcmd_visual_symbol = '[ğŸ€ â®](bold yellow) '
